env:
  global:
    - CODECOV_TOKEN=ecc9ac7e-81ca-41b6-9aa3-5e815ef14738
os:
  - linux
  - osx
language: java
jdk:
#   - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
script:
  - ./build.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)  
